### ISSUE TITLE
All PVC going in pending state during peer add operations

### ISSUE THREAD

**Issue by ksandha** [gluster/gluster-csi-driver#101]
1) Create a 2 gd2 pods in GCS cluster.
2) Create a PVC (should go in pending state)
```
[vagrant@kube1 ~]$ kubectl create  -f pvc.yaml 
persistentvolumeclaim/gcs-pvc1 created
[vagrant@kube1 ~]$ kubectl get pvc
NAME       STATUS    VOLUME   CAPACITY   ACCESS MODES   STORAGECLASS    AGE
gcs-pvc1   Pending                                      glusterfs-csi   32s
```
3) Add the 3rd pods in gd2 gcs cluster.
```
[root@gluster-kube1-0 /]# glustercli peer add gluster-kube1-0.glusterd2.gcs:24008 --endpoints=http://10.233.64.10:24007
Peer add successful
+--------------------------------------+-----------------+-------------------------------------+-------------------------------------+
|                  ID                  |      NAME       |          CLIENT ADDRESSES           |           PEER ADDRESSES            |
+--------------------------------------+-----------------+-------------------------------------+-------------------------------------+
| b693721c-3f32-4c46-aa6e-e98ba18112cc | gluster-kube1-0 | gluster-kube1-0.glusterd2.gcs:24007 | gluster-kube1-0.glusterd2.gcs:24008 |
+--------------------------------------+-----------------+-------------------------------------+-------------------------------------+
[root@gluster-kube1-0 /]# 
[root@gluster-kube1-0 /]# glustercli peer status --endpoints=http://10.233.64.10:24007
+--------------------------------------+-----------------+-------------------------------------+-------------------------------------+--------+-----+
|                  ID                  |      NAME       |          CLIENT ADDRESSES           |           PEER ADDRESSES            | ONLINE | PID |
+--------------------------------------+-----------------+-------------------------------------+-------------------------------------+--------+-----+
| 0e524ecc-cb3f-4b71-a051-07ee0135119f | gluster-kube2-0 | gluster-kube2-0.glusterd2.gcs:24007 | gluster-kube2-0.glusterd2.gcs:24008 | yes    |  24 |
| b693721c-3f32-4c46-aa6e-e98ba18112cc | gluster-kube1-0 | gluster-kube1-0.glusterd2.gcs:24007 | gluster-kube1-0.glusterd2.gcs:24008 | yes    |  22 |
| f003d36a-f584-403b-96b7-66865791b51b | gluster-kube3-0 | gluster-kube3-0.glusterd2.gcs:24007 | gluster-kube3-0.glusterd2.gcs:24008 | yes    |  22 |
+--------------------------------------+-----------------+-------------------------------------+-------------------------------------+--------+-----+
[root@gluster-kube1-0 /]# 
```
4) Create a new pvc . The new PVC going in pending state.
```
[vagrant@kube1 ~]$ kubectl create  -f pvc.yaml 
persistentvolumeclaim/gcs-pvc2 created
[vagrant@kube1 ~]$ 
[vagrant@kube1 ~]$ kubectl get pvc
NAME       STATUS    VOLUME   CAPACITY   ACCESS MODES   STORAGECLASS    AGE
gcs-pvc1   Pending                                      glusterfs-csi   2m42s
gcs-pvc2   Pending                                      glusterfs-csi   4s
[vagrant@kube1 ~]$ 
[vagrant@kube1 ~]$ kubectl get pvc 
NAME       STATUS    VOLUME   CAPACITY   ACCESS MODES   STORAGECLASS    AGE
gcs-pvc1   Pending                                      glusterfs-csi   10m
gcs-pvc2   Pending                                      glusterfs-csi   8m2s

```

5) Check for the cluster status 
```
[vagrant@kube1 ~]$ 
[vagrant@kube1 ~]$ kubectl get pods -n gcs
NAME                                   READY   STATUS    RESTARTS   AGE
csi-attacher-glusterfsplugin-0         2/2     Running   0          27h
csi-nodeplugin-glusterfsplugin-lwzzq   2/2     Running   0          27h
csi-nodeplugin-glusterfsplugin-p8hgt   2/2     Running   0          27h
csi-nodeplugin-glusterfsplugin-wkv7r   2/2     Running   0          27h
csi-provisioner-glusterfsplugin-0      3/3     Running   0          27h
etcd-4cj2v42rq8                        1/1     Running   0          27h
etcd-6k2dp5dv8b                        1/1     Running   0          27h
etcd-965nvhqndk                        1/1     Running   0          27h
etcd-operator-7cb5bd459b-r7c2z         1/1     Running   0          27h
gluster-kube1-0                        1/1     Running   1          22h
gluster-kube2-0                        1/1     Running   1          22h
gluster-kube3-0                        1/1     Running   1          22h
[vagrant@kube1 ~]$ 

```

**Comment by Madhu-1** [comment]
Have you added devices to the newly added glusterd2 pod.
If yes, please provide glusterd2 logs and csi provision logs which helps
for debugging.

**Comment by Madhu-1** [comment]
If newly added glusterd2 pod does not have devices attached to it, CSI driver will not be able to create replica 3 volumes.

**Comment by ksandha** [comment]
New gd2 pod has devices attached. I will shortly attach the logs.

**Comment by ksandha** [comment]
[csi.log](https://github.com/gluster/gluster-csi-driver/files/2606857/csi.log)
[glusterd2.log](https://github.com/gluster/gluster-csi-driver/files/2606858/glusterd2.log)

**Comment by ksandha** [comment]
@Madhu-1 I see log flooding in glusterd2.log . Is it expected or some weird behaviour happening?

**Comment by Madhu-1** [comment]
This is based on the retry going to done by CSI driver, I think this is expected, the request to the CSI driver will be sent by the sidecar containers.

**Comment by Madhu-1** [comment]
need a log from `gluster-provisioner` container in provisioner pod.

**Comment by Madhu-1** [comment]
@ksandha any update on this issue?

**Comment by ksandha** [comment]
@Madhu-1  i will reproduce this issue again as i accidentally deleted the set-up , couldn't collect the logs of the specific container from the cluster.

**Comment by ksandha** [comment]
[vagrant@kube1 ~]$ kubectl -n gcs logs csi-provisioner-glusterfsplugin-0 csi-provisioner
I1128 05:51:19.662256       1 csi-provisioner.go:82] Version: v0.4.0-rc.1-5-gf2ffed45
I1128 05:51:19.662702       1 csi-provisioner.go:96] Building kube configs for running in cluster...
I1128 05:52:44.593217       1 controller.go:572] Starting provisioner controller org.gluster.glusterfs_csi-provisioner-glusterfsplugin-0_d389fe28-f2d1-11e8-839a-0a580ae94009!
I1128 05:52:44.693603       1 controller.go:621] Started provisioner controller org.gluster.glusterfs_csi-provisioner-glusterfsplugin-0_d389fe28-f2d1-11e8-839a-0a580ae94009!
I1128 06:40:24.403631       1 controller.go:927] provision "default/gcs-pvc1" class "glusterfs-csi": started
I1128 06:40:24.437181       1 event.go:221] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"default", Name:"gcs-pvc1", UID:"7c167cab-f2d8-11e8-bee7-5254002fa4e8", APIVersion:"v1", ResourceVersion:"8103", FieldPath:""}): type: 'Normal' reason: 'Provisioning' External provisioner is provisioning volume for claim "default/gcs-pvc1"
I1128 06:40:26.358678       1 controller.go:551] successfully created PV {GCEPersistentDisk:nil AWSElasticBlockStore:nil HostPath:nil Glusterfs:nil NFS:nil RBD:nil ISCSI:nil Cinder:nil CephFS:nil FC:nil Flocker:nil FlexVolume:nil AzureFile:nil VsphereVolume:nil Quobyte:nil AzureDisk:nil PhotonPersistentDisk:nil PortworxVolume:nil ScaleIO:nil Local:nil StorageOS:nil CSI:&CSIPersistentVolumeSource{Driver:org.gluster.glusterfs,VolumeHandle:pvc-7c167cab-f2d8-11e8-bee7-5254002fa4e8,ReadOnly:false,FSType:ext4,VolumeAttributes:map[string]string{glusterbkpservers: gluster-kube1-0.glusterd2.gcs:gluster-kube2-0.glusterd2.gcs,glusterserver: gluster-kube3-0.glusterd2.gcs,glustervol: pvc-7c167cab-f2d8-11e8-bee7-5254002fa4e8,storage.kubernetes.io/csiProvisionerIdentity: 1543384279692-8081-org.gluster.glusterfs,},ControllerPublishSecretRef:nil,NodeStageSecretRef:nil,NodePublishSecretRef:nil,}}
I1128 06:40:26.360801       1 controller.go:1027] provision "default/gcs-pvc1" class "glusterfs-csi": volume "pvc-7c167cab-f2d8-11e8-bee7-5254002fa4e8" provisioned
I1128 06:40:26.360842       1 controller.go:1041] provision "default/gcs-pvc1" class "glusterfs-csi": trying to save persistentvolume "pvc-7c167cab-f2d8-11e8-bee7-5254002fa4e8"
I1128 06:40:26.389881       1 controller.go:1048] provision "default/gcs-pvc1" class "glusterfs-csi": persistentvolume "pvc-7c167cab-f2d8-11e8-bee7-5254002fa4e8" saved
I1128 06:40:26.389937       1 controller.go:1089] provision "default/gcs-pvc1" class "glusterfs-csi": succeeded
I1128 06:40:26.390022       1 controller.go:927] provision "default/gcs-pvc1" class "glusterfs-csi": started
I1128 06:40:26.392183       1 event.go:221] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"default", Name:"gcs-pvc1", UID:"7c167cab-f2d8-11e8-bee7-5254002fa4e8", APIVersion:"v1", ResourceVersion:"8103", FieldPath:""}): type: 'Normal' reason: 'ProvisioningSucceeded' Successfully provisioned volume pvc-7c167cab-f2d8-11e8-bee7-5254002fa4e8
I1128 06:40:26.400877       1 controller.go:936] provision "default/gcs-pvc1" class "glusterfs-csi": persistentvolume "pvc-7c167cab-f2d8-11e8-bee7-5254002fa4e8" already exists, skipping
I1128 08:05:26.467424       1 controller.go:1098] delete "pvc-7c167cab-f2d8-11e8-bee7-5254002fa4e8": started
I1128 08:05:27.214262       1 controller.go:1126] delete "pvc-7c167cab-f2d8-11e8-bee7-5254002fa4e8": volume deleted
I1128 08:05:27.253018       1 controller.go:1136] delete "pvc-7c167cab-f2d8-11e8-bee7-5254002fa4e8": persistentvolume deleted
I1128 08:05:27.253051       1 controller.go:1138] delete "pvc-7c167cab-f2d8-11e8-bee7-5254002fa4e8": succeeded
I1128 09:40:28.723323       1 controller.go:927] provision "default/gcs-pvc1" class "glusterfs-csi": started
I1128 09:40:28.776159       1 event.go:221] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"default", Name:"gcs-pvc1", UID:"a3f71a18-f2f1-11e8-bee7-5254002fa4e8", APIVersion:"v1", ResourceVersion:"29693", FieldPath:""}): type: 'Normal' reason: 'Provisioning' External provisioner is provisioning volume for claim "default/gcs-pvc1"
W1128 09:40:28.800870       1 controller.go:686] Retrying syncing claim "default/gcs-pvc1" because failures 0 < threshold 15
E1128 09:40:28.800937       1 controller.go:701] error syncing claim "default/gcs-pvc1": failed to provision volume with StorageClass "glusterfs-csi": rpc error: code = Internal desc = failed to create volume: no space available or all the devices are not registered
I1128 09:40:28.800979       1 controller.go:927] provision "default/gcs-pvc1" class "glusterfs-csi": started
I1128 09:40:28.801221       1 event.go:221] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"default", Name:"gcs-pvc1", UID:"a3f71a18-f2f1-11e8-bee7-5254002fa4e8", APIVersion:"v1", ResourceVersion:"29693", FieldPath:""}): type: 'Warning' reason: 'ProvisioningFailed' failed to provision volume with StorageClass "glusterfs-csi": rpc error: code = Internal desc = failed to create volume: no space available or all the devices are not registered
I1128 09:40:28.814655       1 event.go:221] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"default", Name:"gcs-pvc1", UID:"a3f71a18-f2f1-11e8-bee7-5254002fa4e8", APIVersion:"v1", ResourceVersion:"29694", FieldPath:""}): type: 'Normal' reason: 'Provisioning' External provisioner is provisioning volume for claim "default/gcs-pvc1"
W1128 09:40:28.834904       1 controller.go:686] Retrying syncing claim "default/gcs-pvc1" because failures 1 < threshold 15
E1128 09:40:28.834940       1 controller.go:701] error syncing claim "default/gcs-pvc1": failed to provision volume with StorageClass "glusterfs-csi": rpc error: code = Internal desc = failed to create volume: no space available or all the devices are not registered
I1128 09:40:28.834967       1 event.go:221] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"default", Name:"gcs-pvc1", UID:"a3f71a18-f2f1-11e8-bee7-5254002fa4e8", APIVersion:"v1", ResourceVersion:"29694", FieldPath:""}): type: 'Warning' reason: 'ProvisioningFailed' failed to provision volume with StorageClass "glusterfs-csi": rpc error: code = Internal desc = failed to create volume: no space available or all the devices are not registered
I1128 09:40:43.801281       1 controller.go:927] provision "default/gcs-pvc1" class "glusterfs-csi": started
I1128 09:40:43.817843       1 event.go:221] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"default", Name:"gcs-pvc1", UID:"a3f71a18-f2f1-11e8-bee7-5254002fa4e8", APIVersion:"v1", ResourceVersion:"29694", FieldPath:""}): type: 'Normal' reason: 'Provisioning' External provisioner is provisioning volume for claim "default/gcs-pvc1"
W1128 09:40:43.838011       1 controller.go:686] Retrying syncing claim "default/gcs-pvc1" because failures 2 < threshold 15
E1128 09:40:43.838060       1 controller.go:701] error syncing claim "default/gcs-pvc1": failed to provision volume with StorageClass "glusterfs-csi": rpc error: code = Internal desc = failed to create volume: no space available or all the devices are not registered
I1128 09:40:43.838108       1 event.go:221] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"default", Name:"gcs-pvc1", UID:"a3f71a18-f2f1-11e8-bee7-5254002fa4e8", APIVersion:"v1", ResourceVersion:"29694", FieldPath:""}): type: 'Warning' reason: 'ProvisioningFailed' failed to provision volume with StorageClass "glusterfs-csi": rpc error: code = Internal desc = failed to create volume: no space available or all the devices are not registered
I1128 09:41:43.838414       1 controller.go:927] provision "default/gcs-pvc1" class "glusterfs-csi": started
I1128 09:41:43.852861       1 event.go:221] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"default", Name:"gcs-pvc1", UID:"a3f71a18-f2f1-11e8-bee7-5254002fa4e8", APIVersion:"v1", ResourceVersion:"29694", FieldPath:""}): type: 'Normal' reason: 'Provisioning' External provisioner is provisioning volume for claim "default/gcs-pvc1"
W1128 09:41:43.876377       1 controller.go:686] Retrying syncing claim "default/gcs-pvc1" because failures 3 < threshold 15
E1128 09:41:43.876422       1 controller.go:701] error syncing claim "default/gcs-pvc1": failed to provision volume with StorageClass "glusterfs-csi": rpc error: code = Internal desc = failed to create volume: no space available or all the devices are not registered
I1128 09:41:43.876904       1 event.go:221] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"default", Name:"gcs-pvc1", UID:"a3f71a18-f2f1-11e8-bee7-5254002fa4e8", APIVersion:"v1", ResourceVersion:"29694", FieldPath:""}): type: 'Warning' reason: 'ProvisioningFailed' failed to provision volume with StorageClass "glusterfs-csi": rpc error: code = Internal desc = failed to create volume: no space available or all the devices are not registered
I1128 09:43:43.876844       1 controller.go:927] provision "default/gcs-pvc1" class "glusterfs-csi": started
I1128 09:43:43.891557       1 event.go:221] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"default", Name:"gcs-pvc1", UID:"a3f71a18-f2f1-11e8-bee7-5254002fa4e8", APIVersion:"v1", ResourceVersion:"29694", FieldPath:""}): type: 'Normal' reason: 'Provisioning' External provisioner is provisioning volume for claim "default/gcs-pvc1"
W1128 09:43:43.911766       1 controller.go:686] Retrying syncing claim "default/gcs-pvc1" because failures 4 < threshold 15
E1128 09:43:43.911820       1 controller.go:701] error syncing claim "default/gcs-pvc1": failed to provision volume with StorageClass "glusterfs-csi": rpc error: code = Internal desc = failed to create volume: no space available or all the devices are not registered
I1128 09:43:43.911878       1 event.go:221] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"default", Name:"gcs-pvc1", UID:"a3f71a18-f2f1-11e8-bee7-5254002fa4e8", APIVersion:"v1", ResourceVersion:"29694", FieldPath:""}): type: 'Warning' reason: 'ProvisioningFailed' failed to provision volume with StorageClass "glusterfs-csi": rpc error: code = Internal desc = failed to create volume: no space available or all the devices are not registered
I1128 09:47:43.912225       1 controller.go:927] provision "default/gcs-pvc1" class "glusterfs-csi": started
I1128 09:47:43.935184       1 event.go:221] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"default", Name:"gcs-pvc1", UID:"a3f71a18-f2f1-11e8-bee7-5254002fa4e8", APIVersion:"v1", ResourceVersion:"29694", FieldPath:""}): type: 'Normal' reason: 'Provisioning' External provisioner is provisioning volume for claim "default/gcs-pvc1"
W1128 09:47:43.957162       1 controller.go:686] Retrying syncing claim "default/gcs-pvc1" because failures 5 < threshold 15
E1128 09:47:43.957206       1 controller.go:701] error syncing claim "default/gcs-pvc1": failed to provision volume with StorageClass "glusterfs-csi": rpc error: code = Internal desc = failed to create volume: no space available or all the devices are not registered
I1128 09:47:43.957712       1 event.go:221] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"default", Name:"gcs-pvc1", UID:"a3f71a18-f2f1-11e8-bee7-5254002fa4e8", APIVersion:"v1", ResourceVersion:"29694", FieldPath:""}): type: 'Warning' reason: 'ProvisioningFailed' failed to provision volume with StorageClass "glusterfs-csi": rpc error: code = Internal desc = failed to create volume: no space available or all the devices are not registered
[vagrant@kube1 ~]$

**Comment by Madhu-1** [comment]
>failed to create volume: no space available or all the devices are not registered

this is the issue with the gd2 , not with the CSI driver

**Comment by Madhu-1** [comment]
@ksandha we need to move this issue to gd2 instead of CSI driver

**Comment by ksandha** [comment]
Okay replicating it there. @Madhu-1

**Comment by Madhu-1** [comment]
@ksandha please close this issue once you move it to gd2.

**Comment by ksandha** [comment]
Cloned the issue hence closing it in CSI branch.
