### ISSUE TITLE
CSI pods going in Crashloopbackoff mode after creating the GCS setup

### ISSUE THREAD

**Issue by ksandha** [gluster/gluster-csi-driver#107]
**Describe the bug**
After creating the GCS setup using vagrant the CSI pods are going in Crashloopbackoff. 

**Steps to reproduce**
1) Create a GCS setup using vagrant 
2) Login to the cluster vagrant ssh kube1 
3) Check the state of the cluster. 
```
[vagrant@kube1 ~]$ kubectl get pods -n gcs
NAME                                   READY   STATUS             RESTARTS   AGE
csi-attacher-glusterfsplugin-0         1/2     CrashLoopBackOff   17         83m
csi-nodeplugin-glusterfsplugin-5gqbt   1/2     CrashLoopBackOff   20         83m
csi-nodeplugin-glusterfsplugin-jcb9v   1/2     CrashLoopBackOff   20         83m
csi-nodeplugin-glusterfsplugin-qt25s   1/2     CrashLoopBackOff   20         83m
csi-provisioner-glusterfsplugin-0      2/3     CrashLoopBackOff   20         83m
etcd-gp64thnjx8                        1/1     Running            0          89m
etcd-jtscxn5vgw                        1/1     Running            0          87m
etcd-k6424x6jlx                        1/1     Running            0          90m
etcd-operator-7cb5bd459b-w5zvd         1/1     Running            0          92m
gluster-kube1-0                        1/1     Running            0          87m
gluster-kube2-0                        1/1     Running            0          87m
gluster-kube3-0                        1/1     Running            1          87m
[vagrant@kube1 ~]$  kubectl get sts 
No resources found.
[vagrant@kube1 ~]$ 
```

**Actual results**
CSI pods going in CrashloopbackOff mode. 

**Expected behavior**
The Pods should be in ready state.

**Comment by ksandha** [comment]
@humblec  Okay will redeploy and revert on the same.

**Comment by ksandha** [comment]
@humblec now deployments are working fine.

**Comment by Madhu-1** [comment]
@humblec can you upload the old `gluster-csi-driver` image to `dockerhub`. as new changes include csiv.1.0.0 which will not work with GCS.

**Comment by Madhu-1** [comment]
i will close this issue once we upload the image to dockerhub

**Comment by Madhu-1** [comment]
@humblec ping.

**Comment by JohnStrunk** [comment]
gluster/gluster-csi-driver image is an autobuild from master.

**Comment by Madhu-1** [comment]
>gluster/gluster-csi-driver image is an autobuild from master.

supports only kubernetes 1.13 as master build on `CSI v1.0.0` spec. currently, GCS supports only kubernetes `1.12` so each time we merge a change in this repo, updates the docker image in docker hub.

**Comment by ksandha** [comment]
Any updates on when will it be resolved. QE's set-ups are blocked with this.

**Comment by Madhu-1** [comment]
we need someone who is having permission to `dockerhub/gluster` to resolve this issue.

**Comment by JohnStrunk** [comment]
Can we either get a PR into GCS to update to 1.13 or revert the update in this repo?

**Comment by Madhu-1** [comment]
we can't update `GCS` to kubernetes 1.13 beta version, `kubespray` supports the installation of stable releases.
let me send a PR to revert back the changes.
