### ISSUE TITLE
REST spec

### ISSUE THREAD

**Issue by lelvisl** [gluster/gluster-csi-driver#126]
```yams
            - name: REST_URL
              value: http://192.168.121.182:24007
            - name: REST_SECRET
              value: b03045b7988258557ecd3e136cd37ba3f928ea0831b3b1b7ed8ae238d36d9071
```

Where I can get this variables for my environment?

**Comment by Madhu-1** [comment]
these are the variables used to communicate with glusterd2 if you have deployed the glusterd2 cluster manually in kubernetes or outside of kubernetes.
`REST_URL` - is the URL where your glusterd2 service is listening
`REST_SECRET` - is the secret used of authentication with glusterd2.

if you want to deploy the gluster-csi-driver without changing all these try our [GCS](https://github.com/gluster/gcs/blob/master/deploy/README.md) repo


GCS deploys following components
- Kubernetes 
- ETCD cluster
- gusterd2 cluster
- gluster-csi-driver
- Prometheus for metrics.

**Comment by Madhu-1** [comment]
@lelvisl hope my comment helps you, please free to reopen this issue if  not
