### ISSUE TITLE
don't return UNKNOWN in capabilities

### ISSUE THREAD

**Issue by jdef** [gluster/gluster-csi-driver#147]
**Describe the bug**
CSI spec uses UNKNOWN w/ enumerations for compatibility across different versions of the spec. For example, if a plugin using a newer version of the spec passes an enumeration value to a CO that was built on a slightly older version of the spec, for which said enum value is not defined, the CO would decode that value as UNKNOWN. It is NOT intended that plugins or CO's intentionally pass UNKNOWN enum values in CSI requestss/responses.

e.g. https://github.com/gluster/gluster-csi-driver/blob/e72f47614eda3c10bb5205462ce5ab099f558a4d/pkg/glusterfs/nodeserver.go#L164

**Comment by humblec** [comment]
@jdef Sure, thanks for pointing it out! Let us take care of this.
