### ISSUE TITLE
thin-arbiter volume type support

### ISSUE THREAD

**Issue by atinmu** [gluster/gluster-csi-driver#151]
**Describe the feature you'd like to have.**
thin-arbiter support in the storage class to ensure with GCS deployment one can create a thin arbiter volume.

**What is the value to the end user? (why is it a priority?)**
https://docs.gluster.org/en/latest/Administrator%20Guide/Thin-Arbiter-Volumes/

How would the end user gain value from having this feature?
https://docs.gluster.org/en/latest/Administrator%20Guide/Thin-Arbiter-Volumes/

-----

Child of #46

**Comment by Madhu-1** [comment]
assigning  it to  humble as he is already working on  this one
