### ISSUE TITLE
push loopback driver to dockerhub

### ISSUE THREAD

**Issue by Madhu-1** [gluster/gluster-csi-driver#157]
Need to create a automated build job for loopback CSI in dockerhub

**Comment by Madhu-1** [comment]
@amarts ^^

**Comment by Madhu-1** [comment]
@JohnStrunk @kshlm @nigelbabu can you guys help here.

**Comment by amarts** [comment]
@kotreshhr not sure you too was working on this piece.

**Comment by kotreshhr** [comment]
@amarts Nope, I was about to check with @kshlm or @nigelbabu about this.

**Comment by JohnStrunk** [comment]
I'll work on this today
