### ISSUE TITLE
Create a deploy script which does container build and push to container registry.

### ISSUE THREAD

**Issue by humblec** [gluster/gluster-csi-driver#17]
As part of this, we need to create a script which does an automatic build and push of container tagged with driver version as in https://github.com/kubernetes-incubator/external-storage/blob/master/deploy.sh.  We can integrate it with Travis and make sure each PR go through the same process.

**Comment by humblec** [comment]
The integration can be done with any of it for now. If centos-ci is readily available we can consume it.

**Comment by JohnStrunk** [comment]
Can't this be done w/ git triggers directly via quay?

**Comment by amarts** [comment]
I was thinking of getting a job to build, test, and then push the containers to repo (if there is a change in the repo), every night like we did for gd2 :+1:  https://review.gluster.org/#/c/build-jobs/+/20873/

I would say we shouldn't be bothered much about updating the image for merging PR, but should be planning to do it only if we are passing the tests, once the tests are setup.

**Comment by humblec** [comment]
@amarts agree. Even I was thinking same way, ideally once the tests are passed we can build and push that image to regitry. It can be tagged as `dev` and triggered with each PR merge.

**Comment by humblec** [comment]
@nigelbabu would you like to send a PR for CSI repo similar to glusterd2 ?

**Comment by nigelbabu** [comment]
Yep, I can pick this up once there's something to build.

**Comment by humblec** [comment]
Thanks @nigelbabu !

**Comment by humblec** [comment]
@nigelbabu the initial PR Is merged, so please feel free to send this PR.

**Comment by JohnStrunk** [comment]
Could someone please explain the need for a "script" to do any of this?

Both buildah and docker support multi stage build, meaning we should be able to go from source to container with just quay or docker hub.
They support pattern matching against branches or tags, ensuring consistent image tagging, and builds are triggered upon commit, keeping them up to date.

Commits won't be merge until they pass tests, so manual gating should not be necessary.

**Comment by JohnStrunk** [comment]
@nigelbabu Any luck configuring docker hub?

**Comment by nigelbabu** [comment]
I've done a test automated build project - https://hub.docker.com/r/gluster/gluster-csi-driver/

If this works well, I'd like to delete this and replace the current image with this one. Please let me know if that's alright?

**Comment by nigelbabu** [comment]
Gah, build failed: https://hub.docker.com/r/gluster/gluster-csi-driver/builds/b29p4oky78zxxrlt2dmq4sg/

**Comment by atinmu** [comment]
@nigelbabu would this make into GCS/0.3 or you want to buy in more time? If so, please move it to GCS/0.4. You might have to create the GCS/0.4 label in this repo which might not be present yet.

**Comment by JohnStrunk** [comment]
The issue with the build was the inability to set the build context via the interface on hub.docker. We have moved the build to their cloud.docker.com interface and it's working. I believe we can close this as we have auto-builds working. It should also auto-tag images corresponding to git version tags as well.

https://cloud.docker.com/u/gluster/repository/docker/gluster/gluster-csi-driver

pull via: `docker pull gluster/gluster-csi-driver:latest`
