### ISSUE TITLE
Add unit tests for CSI driver functions

### ISSUE THREAD

**Issue by humblec** [gluster/gluster-csi-driver#19]
We have to add unit tests for CSI driver functions and run it with each PR. 

- [ ] This unit tests should be against CSI spec 0.3
- [ ] Should cover postive and negative test cases.
- [ ] should use kubernetes/csi-test framework

**Comment by humblec** [comment]
Fixed @ #16

**Comment by Madhu-1** [comment]
@humblec @JohnStrunk I think we can close this one also

**Comment by humblec** [comment]
Yes. closing it!
