### ISSUE TITLE
Move Dockerfile to root & investigate multi-stage build

### ISSUE THREAD

**Issue by JohnStrunk** [gluster/gluster-csi-driver#36]
**Describe the feature you'd like to have.**
Buildah wants the Dockerfile to be at the root, so in order for the CSI driver to support buildah in addition to docker for container builds, we need to move the Dockerfile. As a part of this, we should also look at introducing multi-stage container builds.

**What is the value to the end user? (why is it a priority?)**
Supporting both docker & buildah enables users to select their desired build tool, and particularly w/ buildah, builds can be done w/o root privileges.
Additionally, by moving to a fully containerized build process, users & devs don't need to worry about the specifics of configuring their build environment (dep and other utilities). Only a working docker/buildah would be necessary. This also means the container repositories would be able to build minimal containers from source as opposed to having to choose between (1) end containers w/ the build tools in them or (2) having a CI job push a pre-built container.

**How will we know we have a good solution? (acceptance criteria)**
- [x] Verify buildah requirements (Dockerfile placement)
- [x] Verify we can have multiple Dockerfiles in root (for addl csi drivers)
- [ ] Dockerfile moved
- [x] Multi-stage build that incorporates the current `make` and `docker build` steps
- [ ] Preserve method for generating container w/ a driver and dependencies from local machine (to support dev workflow)
- [ ] Docs updated for build process

**Additional context**
Originates from discussion started here: https://github.com/gluster/gluster-csi-driver/pull/33#discussion_r217091977

**Comment by JohnStrunk** [comment]
Following up on this, I was able to use buildah in the existing Dockerfile location.

From repo root:
```
[jstrunk master  gluster-csi-driver]$ buildah bud -t glusterfs-csi-driver -f pkg/glusterfs/Dockerfile .
STEP 1: FROM centos:7.5.1804
Getting image source signatures
Copying blob sha256:7dc0dca2b1516961d6b3200564049db0a6e0410b370bb2189e2efae0d368616f
 71.23 MiB / 71.23 MiB [===================================================] 23s
Copying config sha256:fdf13fa91c6e0445e51dfd26443aa4bcd561fd40a7c5e85718c4df8e67bcc514
 2.15 KiB / 2.15 KiB [======================================================] 0s
Writing manifest to image destination
Storing signatures
STEP 2: COPY ./build/glusterfs-csi-driver /glusterfs-csi-driver
STEP 3: RUN yum -y install glusterfs-fuse && yum clean all -y
... snip ...
STEP 4: ENTRYPOINT ["/glusterfs-csi-driver"]
STEP 5: COMMIT containers-storage:[vfs@/home/jstrunk/.local/share/containers/storage+/run/user/101587/run]localhost/glusterfs-csi-driver:latest
Getting image source signatures
Skipping fetch of repeat blob sha256:bcc97fbfc9e1a709f0eb78c1da59caeb65f43dc32cd5deeb12b8c1784e5b8237
Copying blob sha256:8b87e0bf4cc0d87e6e1713ccde9845c285bdc3103e1c4c5ca619c13310356e03
 18.38 MiB / 18.38 MiB [====================================================] 0s
Copying config sha256:aef86b228db7fd2143414340a4bd259053c0ad939cc0bec78ee4c74604da7d80
 1.22 KiB / 1.22 KiB [======================================================] 0s
Writing manifest to image destination
Storing signatures
--> aef86b228db7fd2143414340a4bd259053c0ad939cc0bec78ee4c74604da7d80

[jstrunk master  gluster-csi-driver]$ buildah images
IMAGE ID             IMAGE NAME                                               CREATED AT             SIZE
fdf13fa91c6e         docker.io/library/centos:7.5.1804                        Aug 6, 2018 15:23      208 MB
aef86b228db7         localhost/glusterfs-csi-driver:latest                    Sep 13, 2018 11:04     282 MB
```

I don't think this means we shouldn't move the Dockerfile. It's just a data point in the discussion.
@nigelbabu Your thoughts?

**Comment by humblec** [comment]
afict, this issue can be closed. @JohnStrunk can you ?

**Comment by JohnStrunk** [comment]
The PR for this, #65 had been blocked by #53.
I can now integrate w/ Travis and write the docs.
