### ISSUE TITLE
Add Travis-ci

### ISSUE THREAD

**Issue by JohnStrunk** [gluster/gluster-csi-driver#41]
**Describe the feature you'd like to have.**
Travis-ci should be enabled for this repo to handle pre-merge checks. Travis is much more lightweight (and commonly used) than centos-ci. I would like to have travis for linting and unit tests, reserving centos-ci for e2e testing.

**What is the value to the end user? (why is it a priority?)**
Robust linting and unit tests via travis provide an easily visible and configurable method for ensuring a base level of quality is maintained. Additionally, Travis tests are executed on all PRs w/o waiting for admin approval. This provides immediate feedback to contributors, allowing them to refine their code without committer involvement.

**How will we know we have a good solution? (acceptance criteria)**
- Linting
  - [x] Shell scripts
  - [x] markdown
  - [x] yaml
- [ ] Compilation with stable and latest golang
- [x] gometalinter
  - This seems to [include](https://github.com/alecthomas/gometalinter#supported-linters) the reasonable set we would want to run
- [ ] Test build of the container(s) with docker and buildah
- [ ] Documentation of the Travis setup

**Additional context**
The above checklist is largely derived from the existing centos-ci tests

**Comment by humblec** [comment]
@JohnStrunk what is pending here ? If nothing can we close this issue ?
