### ISSUE TITLE
PVC deletion causes hung/(terminating status) which is in mounted state 

### ISSUE THREAD

**Issue by rmadaka** [gluster/gluster-csi-driver#62]
**Describe the bug**
Trying to delete the PVC which is mounted to some app pod and mount point is having some I/O's on it, PVC deletion not coming out from terminal and after given ctrl+c verified pvc status, pvc status is in terminating state.

**Steps to reproduce**

-> Create a PVC (auto provisioning volume)
-> Mount PVC to some app pod.
-> Then run I/O's on mount point.
-> Try to delete pvc from kubernetes master using 'kubectl delete pvc/, it will give the message like pvc deleted but it will not come out from terminal.

$ kubectl delete pvc/glusterfs-csi-pv1
persistentvolumeclaim "glusterfs-csi-pv1" deleted

ctrl+c

-> After ctrl+c given , verified pvc status, pvc status went to terminating state.

$ kubectl get pvc
NAME STATUS VOLUME CAPACITY ACCESS MODES STORAGECLASS AGE
glusterfs-csi-pv1 Terminating pvc-fa591562bfe011e8 2Gi RWX glusterfs-csi 20h

-> Deleted app pod where pvc is mounte

**Actual results**
Trying to delete the PVC which is mounted to some app pod and mount point is having some I/O's on it, PVC deletion not coming out from terminal and after given ctrl+c verified pvc status, pvc status is in terminating state.

**Expected behavior**
PVC deletion should throw an error message saying that pvc is in mounted state.

**Additional context**

**Comment by JohnStrunk** [comment]
@rmadaka The behavior you have described is as intended by Kubernetes.

"Storage object in use" protection was introduced as beta in 1.10 and stable 1.11. It prevents PVCs and PVs from being deleted while they are in use. The behavior you describe, above, corresponds to "Scenario 2" here: https://kubernetes.io/docs/tasks/administer-cluster/storage-object-in-use-protection/#scenario-2-the-pvc-is-in-active-use-by-a-pod

**Comment by rmadaka** [comment]
Closing this issue as it is expected behavior in kubernetes as mentioned in above article.
