### ISSUE TITLE
Travis failing due to long-running gometalinter

### ISSUE THREAD

**Issue by JohnStrunk** [gluster/gluster-csi-driver#68]
**Describe the bug**
Travis has a timeout wherein it will kill a job if there is no output received for 10 minutes. While I hadn't encountered a problem in testing, we seem to be hitting it now that it is merged. :cry: 

**Steps to reproduce**

1. Example: https://travis-ci.com/gluster/gluster-csi-driver/jobs/149681137

**Comment by humblec** [comment]
Yes, , Ref Discussion# https://github.com/gluster/gluster-csi-driver/pull/67
