### ISSUE TITLE
Gluster volume naming based on PVC name

### ISSUE THREAD

**Issue by JohnStrunk** [gluster/gluster-csi-driver#71]
**Describe the feature you'd like to have.**
It should be possible to propagate storage application context down to gluster. [OCS 3.10](https://redhatstorage.redhat.com/2018/09/) added the ability to influence the name of the underlying gluster volume based on the PVC that was used to provision it. This happens by specifying a "custom prefix" in the StorageClass, and based upon that, the underlying gluster volume that backs the PVC takes the form of `<prefix>-<pvc_namespace>-<pvc_name>-UUID`.

**What is the value to the end user? (why is it a priority?)**
This feature is required to assist administrators that are trying to use traditional backup software with kubernetes-based storage. They need a way, from outside the kube cluster, to locate the data that a containerized application uses. By having custom naming, `glustercli volume list` could be used to locate the volumes and mount them with a legacy backup application.

**How will we know we have a good solution? (acceptance criteria)**
- Given information about an application running in the kubernetes environment, it should be possible to locate the Gluster volume(s) that it uses.
- The backup host shouldn't need to directly query the kube API
- The solution should work efficiently even with 1000s of volumes
- It needs to be able to recognize scenarios where a PVC is deleted and recreated with the same name/ns.
- These capabilities should be applicable to restore as well.

**Additional context**
- Custom naming of the volume is one option for tying application context to the volume. It is also possible to use volume-level tags in GD2.
- Getting access to the PVC name/namespace may require an upcall by the CSI driver to kube, breaking the multi-orchestrator nature.
- Depending on where the PV name gets created, it may be possible to do this with modified kube/csi sidecar containers

**Comment by aravindavk** [comment]
+1

This will surely help debugging.

**Comment by JohnStrunk** [comment]
Madhu pointed out I already had an issue for this open. Closing in favor of the original.
