### ISSUE TITLE
Create CSI glusterfs driver for GD2 

### ISSUE THREAD

**Issue by humblec** [gluster/gluster-csi-driver#8]
The CSI driver should be capable of doing below tasks with GD2 API.

- [x] Volume provisioning 
- [x] Volume detele
- [x] Mount 
- [x] Unmount volume

ps# Migrate  https://github.com/gluster/gluster-csi-driver/pull/1 to GD2 API

**Comment by humblec** [comment]
[status] Its almost done, as soon as design PR is pushed, I will push the code.

**Comment by amarts** [comment]
Thanks for this @humblec 

As a stretch effort, @Madhu-1 with few other GD2 devs got some basic CSI written for GD2 too. Expect a PR too. 

Good if we can collaborate and get it reviewed and merged soon.

**Comment by humblec** [comment]
I had it ready for some time and was working on design PR which is the must `frist` thing here :),  no worries, I will talk to @madhu-1 and colloborate or seek help in addressing other issues in this repo. I have already assigned one to him.

**Comment by humblec** [comment]
This is addressed via PR https://github.com/gluster/gluster-csi-driver/pull/11 and followed up via https://github.com/gluster/gluster-csi-driver/pull/16

**Comment by Madhu-1** [comment]
@humblec can we close this one also

**Comment by Madhu-1** [comment]
@humblec ping, can we close this one

**Comment by humblec** [comment]
This is done. thanks !
