### ISSUE TITLE
update latest image in docker-hub

### ISSUE THREAD

**Issue by Madhu-1** [gluster/gluster-csi-driver#91]
I see a new image of glusterfs-csi-driver with tag `v0.0.9 `  in dockerhub, but the latest image is 2 months old, are we updating the latest images once we do the new realease

```
v0.0.9            95 MB         3 days ago
latest            94 MB         2 months ago
```

if we are not updating the latest image, then we need to update the GCS repo to point to the new glusterfs-csi-driver new image.

**Comment by JohnStrunk** [comment]
Related: #13 #17

**Comment by humblec** [comment]
@Madhu-1 @JohnStrunk  the latest tag is also updated. Please cross check .

**Comment by Madhu-1** [comment]
now its updated, Thanks :)
